[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120
docstring-quotes = '"""'
inline-quotes = '"'
multiline-quotes = '"""'


[tool.isort]
combine_as_imports = true
line_length = 120
profile = "black"
skip_gitignore = true

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
pretty = true
show_error_codes = true
warn_return_any = true
warn_unused_ignores = true

[tool.pytest.ini_options]
filterwarnings = ["ignore:SelectableGroups dict interface is deprecated. Use select.:DeprecationWarning"]
